name: 'test send Ansible'
description: 'Send files via Ansible'
inputs:
  ssh_key:
    description: 'key for ssh'
    required: true
  host:
    description: 'ip host for ssh'
    required: true
  # user:
  #   description: 'user for ssh'
  #   required: true

runs:
  using: "composite"
  steps:
  - name: Ansible playbook
    uses: dawidd6/action-ansible-playbook@v2
    with:
      # Le fichier de "recette" Ansible
      playbook: ./ansible/playbook.yml
      
      # La clé SSH passée via les inputs
      key: ${{ inputs.ssh_key }}
      
      # Création d'un inventaire "à la volée"
      inventory: |
        [vps]
        ${{ inputs.host }}
      options: |
        --extra-vars "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"