name: 'file creation'
description: 'create file'
inputs:
  secret:
    description: 'secret for test'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create file
      shell: bash
      env:
        SECRET: ${{ inputs.secret }}
      run: |
        echo "<!doctype html>
          <html>
            <body>
              <p>My test from Github Actions !!!</p>
            </body>
          </html>" > cv.html
