name: Ansible files lint check 

on:
  push:
    paths:
      - 'playbook.yml'
      - 'roles/**'
      - 'group_vars/**'
      - '*.yml'
  pull_request:
    paths:
      - 'playbook.yml'
      - 'roles/**'
      - 'group_vars/**'
      - '*.yml'
jobs:
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      args: ''
